import collections
stack=collections.deque()
print(stack)
stack.append(10)
stack.append(20)
stack.append(30)
stack.append(40)
print(stack)
stack.pop()
stack.pop()
stack.pop()
stack.pop()
#stack.pop()
print(stack)